version: "3.9"
services:
  web-octane:
    image: madzone/ironfence-app:v1.1
    container_name: web-octane
    build:
      context: .
      dockerfile: ./docker/Dockerfile.octane
      args:
        PHP_VERSION: '8.3-zts-bullseye'
    ports:
      - "80:80" #http
      - "443:443" #https
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 600M
        reservations:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure