services:
  web-octane:
    image: madzone/ironfence-app:robust-1.11.2
    container_name: ironfence-app
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.3-fpm-bullseye'
    # depends_on:
    #   - redis  
    ports:
      - "8080:8080"
      - "80:80" #http
      - "443:443" #https
    networks:
      - laravel

  # redis:
  #   image: redis:latest
  #   networks:
  #     - laravel

#  meilisearch-harpia:
#    image: getmeili/meilisearch:latest
#    restart: unless-stopped
#    ports:
#      - "7700:7700"
#    volumes:
#      - ./docker/meilisearch/:/var/lib/meilisearch
#    networks:
#      - laravel

networks:
  laravel:
    driver: bridge
