services:
  web-octane:
    image: madzone/ironfence-app:v1.3.1
    container_name: ironfence-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.3-fpm-bullseye'
    depends_on:
      - redis  
    ports:
      - "80:80" #http
      - "443:443" #https
    networks:
      - laravel  

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"  # Limite de CPU aumentado
          memory: 10G   # Limite de memória aumentado
        reservations:
          cpus: "1.0"  # Reserva de CPU aumentada
          memory: 2G   # Reserva de memória aumentada
      restart_policy:
        condition: on-failure
    networks:
      - laravel

  # kibana:
  #     image: kibana:7.17.15
  #     ports:
  #       - "5601:5601"
  #     environment:
  #       ELASTICSEARCH_HOSTS: "http://search:9200"
  #     networks:
  #       - laravel
  
  # search:
  #     container_name: elasticsearch_search
  #     image: elasticsearch:7.17.15
  #     ports:
  #       - 9200:9200
  #     environment:
  #       - discovery.type=single-node
  #       # - ES_JAVA_OPTS=-Xms4g -Xmx4g
  #     networks:
  #       - laravel       
networks:
    laravel:
        driver: bridge            
