name: Build, Push Docker Image, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker docker/Dockerfile build -t ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest .

      # Login no Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Conecta ao servidor de produção via SSH e atualiza o container
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /caminho/para/seu/projeto
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest
            docker-compose down
            docker-compose up -d